name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'

        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v1.2.1

        - name: Configure AWS Credentials For GitHub Actions
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: IaC Apply
          env:
            COMMAND_IAC: terraform
          run: |
            cd infrastructure
            $COMMAND_IAC init
            $COMMAND_IAC validate
            $COMMAND_IAC plan
            $COMMAND_IAC apply -auto-approve
